version: '3'

tasks:
  install-deps:
    desc: Install all dependencies (runtime + dev)
    cmds:
      - poetry install --with dev

  delint:
    desc: Autofix & format code
    cmds:
      - poetry run ruff check --fix-only
      - poetry run ruff format .
      - poetry run mypy . --pretty --strict

  lint:
    desc: Verify code styles & types
    cmds:
      - poetry run ruff check
      - poetry run ruff format . --check
      - poetry run mypy . --pretty --strict

  test:
    desc: Run unit tests with coverage
    deps: [install-deps]
    cmds:
      - poetry run pytest tests/ --cov=liquidity --ignore tests/e2e --cov-report=xml

  test-e2e:
    desc: Run end-to-end tests
    deps: [install-deps]
    cmds:
      - poetry run pytest tests/e2e
