name: CI - Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ci-approval
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Python & install tools
        run: |
          sudo apt-get update
          curl -sSL https://install.python-poetry.org | python3 -
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv ./bin/task /usr/local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: task install-deps

      - name: Run lint
        run: task lint

      - name: Run tests
        run: task test

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
