name: Release to PyPI

on:
  push:
    tags:
      - 'v*'  # Runs only on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 2.1.3
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Validate version tag matches pyproject.toml
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          PROJECT_VERSION=$(poetry version -s)
          if [ "$TAG_VERSION" != "$PROJECT_VERSION" ]; then
            echo "Tag v$TAG_VERSION does not match pyproject.toml version $PROJECT_VERSION"
            exit 1
          fi

      - name: Install dependencies
        run: poetry install --only main

      - name: Build package
        run: poetry build

      - name: Verify with Twine
        run: |
          pip install --no-cache-dir twine
          twine check dist/*

      - name: Publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
